# import json


# with open("timezones.json") as oj: 
#     Timezones = json.load(oj)

# zones = ""

# for zone in Timezones:
#     name = zone["Name"]
#     abreviation = zone["Abbreviation"]
#     zones += (f"create_choice(name={str(name)},value={str(abreviation)}),")


# print(zones)
from random import choices
from discord import Embed
from discord.ext.commands import Bot, Cog
from discord_slash import cog_ext, SlashContext
from discord.ext import commands
from discord_slash.utils.manage_commands import create_choice, create_option
import discord
import discord.utils
import json

class fun(commands.Cog):
    def __init__(self, bot):
        self.bot = bot


    # @cog_ext.cog_slash(name="Timezone conversion", description="",guild_ids=[932684556572700773,786013884216639509,983015288910000188],
    # options=[create_option(
    # name="FromTimezone",
    # description="choose your Timezone",
    # required=True,
    # option_type=3,
    # choices=[
    #         create_choice(name="Alpha Time Zone",value="A"),
    #         create_choice(name="Australian Central Daylight Time",value="ACDT"),
    #         create_choice(name="Australian Central Standard Time",value="ACST"),
    #         create_choice(name="Atlantic Daylight Time",value="ADT"),
    #         create_choice(name="Atlantic Daylight Time",value="ADT"),
    #         create_choice(name="Australian Eastern Daylight Time",value="AEDT"),
    #         create_choice(name="Australian Eastern Standard Time",value="AEST"),
    #         create_choice(name="Afghanistan Time",value="AFT"),
    #         create_choice(name="Alaska Daylight Time",value="AKDT"),
    #         create_choice(name="Alaska Standard Time",value="AKST"),
    #         create_choice(name="Alma-Ata Time",value="ALMT"),
    #         create_choice(name="Armenia Summer Time",value="AMST"),
    #         create_choice(name="Amazon Summer Time",value="AMST"),
    #         create_choice(name="Armenia Time",value="AMT"),
    #         create_choice(name="Amazon Time",value="AMT"),
    #         create_choice(name="Anadyr Summer Time",value="ANAST"),
    #         create_choice(name="Anadyr Time",value="ANAT"),
    #         create_choice(name="Aqtobe Time",value="AQTT"),
    #         create_choice(name="Argentina Time",value="ART"),
    #         create_choice(name="Arabia Standard Time",value="AST"),
    #         create_choice(name="Atlantic Standard Time",value="AST"),
    #         create_choice(name="Australian Western Daylight Time",value="AWDT"),
    #         create_choice(name="Australian Western Standard Time",value="AWST"),
    #         create_choice(name="Azores Summer Time",value="AZOST"),
    #         create_choice(name="Azores Time",value="AZOT"),
    #         create_choice(name="Azerbaijan Summer Time",value="AZST"),
    #         create_choice(name="Azerbaijan Time",value="AZT"),
    #         create_choice(name="Bravo Time Zone",value="B"),
    #         create_choice(name="Brunei Darussalam Time",value="BNT"),
    #         create_choice(name="Bolivia Time",value="BOT"),
    #         create_choice(name="Brasilia Summer Time",value="BRST"),
    #         create_choice(name="BrasÃ­lia time",value="BRT"),
    #         create_choice(name="Bangladesh Standard Time",value="BST"),
    #         create_choice(name="British Summer Time",value="BST"),
    #         create_choice(name="Bhutan Time",value="BTT"),
    #         create_choice(name="Charlie Time Zone",value="C"),
    #         create_choice(name="Casey Time",value="CAST"),
    #         create_choice(name="Central Africa Time",value="CAT"),
    #         create_choice(name="Cocos Islands Time",value="CCT"),
    #         create_choice(name="Cuba Daylight Time",value="CDT"),
    #         create_choice(name="Central Daylight Time",value="CDT"),
    #         create_choice(name="Central European Summer Time",value="CEST"),
    #         create_choice(name="Central European Time",value="CET"),
    #         create_choice(name="Chatham Island Daylight Time",value="CHADT"),
    #         create_choice(name="Chatham Island Standard Time",value="CHAST"),
    #         create_choice(name="Cook Island Time",value="CKT"),
    #         create_choice(name="Chile Summer Time",value="CLST"),
    #         create_choice(name="Chile Standard Time",value="CLT"),
    #         create_choice(name="Colombia Time",value="COT"),
    #         create_choice(name="China Standard Time",value="CST"),
    #         create_choice(name="Central Standard Time",value="CST"),
    #         create_choice(name="Cuba Standard Time",value="CST"),
    #         create_choice(name="Cape Verde Time",value="CVT"),
    #         create_choice(name="Christmas Island Time",value="CXT"),
    #         create_choice(name="Chamorro Standard Time",value="ChST"),
    #         create_choice(name="Delta Time Zone",value="D"),
    #         create_choice(name="Davis Time",value="DAVT"),
    #         create_choice(name="Echo Time Zone",value="E"),
    #         create_choice(name="Easter Island Summer Time",value="EASST"),
    #         create_choice(name="Easter Island Standard Time",value="EAST"),
    #         create_choice(name="Eastern Africa Time",value="EAT"),
    #         create_choice(name="Ecuador Time",value="ECT"),
    #         create_choice(name="Eastern Daylight Time",value="EDT"),
    #         create_choice(name="Eastern European Summer Time",value="EEST"),
    #         create_choice(name="Eastern European Time",value="EET"),
    #         create_choice(name="Eastern Greenland Summer Time",value="EGST"),
    #         create_choice(name="East Greenland Time",value="EGT"),
    #         create_choice(name="Eastern Standard Time",value="EST"),
    #         create_choice(name="Tiempo del Este",value="ET"),
    #         create_choice(name="Foxtrot Time Zone",value="F"),
    #         create_choice(name="Fiji Summer Time",value="FJST"),
    #         create_choice(name="Fiji Time",value="FJT"),
    #         create_choice(name="Falkland Islands Summer Time",value="FKST"),
    #         create_choice(name="Falkland Island Time",value="FKT"),
    #         create_choice(name="Fernando de Noronha Time",value="FNT"),
    #         create_choice(name="Golf Time Zone",value="G"),
    #         create_choice(name="Galapagos Time",value="GALT"),
    #         create_choice(name="Gambier Time",value="GAMT"),
    #         create_choice(name="Georgia Standard Time",value="GET"),
    #         create_choice(name="French Guiana Time",value="GFT"),
    #         create_choice(name="Gilbert Island Time",value="GILT"),
    #         create_choice(name="Greenwich Mean Time",value="GMT"),
    #         create_choice(name="Gulf Standard Time",value="GST"),
    #         create_choice(name="Guyana Time",value="GYT"),
    #         create_choice(name="Hotel Time Zone",value="H"),
    #         create_choice(name="Heure AvancÃ©e de l'Atlantique",value="HAA"),
    #         create_choice(name="Heure AvancÃ©e du Centre",value="HAC"),
    #         create_choice(name="Hawaii-Aleutian Daylight Time",value="HADT"),
    #         create_choice(name="Heure AvancÃ©e de l'Est",value="HAE"),
    #         create_choice(name="Heure AvancÃ©e du Pacifique",value="HAP"),
    #         create_choice(name="Heure AvancÃ©e des Rocheuses",value="HAR"),
    #         create_choice(name="Hawaii-Aleutian Standard Time",value="HAST"),
    #         create_choice(name="Heure AvancÃ©e de Terre-Neuve",value="HAT"),
    #         create_choice(name="Heure AvancÃ©e du Yukon",value="HAY"),
    #         create_choice(name="Hong Kong Time",value="HKT"),
    #         create_choice(name="Hora Legal de Venezuela",value="HLV"),
    #         create_choice(name="Heure Normale de l'Atlantique",value="HNA"),
    #         create_choice(name="Heure Normale du Centre",value="HNC"),
    #         create_choice(name="Heure Normale de l'Est",value="HNE"),
    #         create_choice(name="Heure Normale du Pacifique",value="HNP"),
    #         create_choice(name="Heure Normale des Rocheuses",value="HNR"),
    #         create_choice(name="Heure Normale de Terre-Neuve",value="HNT"),
    #         create_choice(name="Heure Normale du Yukon",value="HNY"),
    #         create_choice(name="Hovd Time",value="HOVT"),
    #         create_choice(name="India Time Zone",value="I"),
    #         create_choice(name="Indochina Time",value="ICT"),
    #         create_choice(name="Israel Daylight Time",value="IDT"),
    #         create_choice(name="Indian Chagos Time",value="IOT"),
    #         create_choice(name="Iran Daylight Time",value="IRDT"),
    #         create_choice(name="Irkutsk Summer Time",value="IRKST"),
    #         create_choice(name="Irkutsk Time",value="IRKT"),
    #         create_choice(name="Iran Standard Time",value="IRST"),
    #         create_choice(name="Israel Standard Time",value="IST"),
    #         create_choice(name="India Standard Time",value="IST"),
    #         create_choice(name="Irish Standard Time",value="IST"),
    #         create_choice(name="Japan Standard Time",value="JST"),
    #         create_choice(name="Kilo Time Zone",value="K"),
    #         create_choice(name="Kyrgyzstan Time",value="KGT"),
    #         create_choice(name="Krasnoyarsk Summer Time",value="KRAST"),
    #         create_choice(name="Krasnoyarsk Time",value="KRAT"),
    #         create_choice(name="Korea Standard Time",value="KST"),
    #         create_choice(name="Kuybyshev Time",value="KUYT"),
    #         create_choice(name="Lima Time Zone",value="L"),
    #         create_choice(name="Lord Howe Daylight Time",value="LHDT"),
    #         create_choice(name="Lord Howe Standard Time",value="LHST"),
    #         create_choice(name="Line Islands Time",value="LINT"),
    #         create_choice(name="Mike Time Zone",value="M"),
    #         create_choice(name="Magadan Summer Time",value="MAGST"),
    #         create_choice(name="Magadan Time",value="MAGT"),
    #         create_choice(name="Marquesas Time",value="MART"),
    #         create_choice(name="Mawson Time",value="MAWT"),
    #         create_choice(name="Mountain Daylight Time",value="MDT"),
    #         create_choice(name="MitteleuropÃ¤ische Sommerzeit",value="MESZ"),
    #         create_choice(name="MitteleuropÃ¤ische Zeit",value="MEZ"),
    #         create_choice(name="Marshall Islands Time",value="MHT"),
    #         create_choice(name="Myanmar Time",value="MMT"),
    #         create_choice(name="Moscow Daylight Time",value="MSD"),
    #         create_choice(name="Moscow Standard Time",value="MSK"),
    #         create_choice(name="Mountain Standard Time",value="MST"),
    #         create_choice(name="Mauritius Time",value="MUT"),
    #         create_choice(name="Maldives Time",value="MVT"),
    #         create_choice(name="Malaysia Time",value="MYT"),
    #         create_choice(name="November Time Zone",value="N"),
    #         create_choice(name="New Caledonia Time",value="NCT"),
    #         create_choice(name="Newfoundland Daylight Time",value="NDT"),
    #         create_choice(name="Norfolk Time",value="NFT"),
    #         create_choice(name="Novosibirsk Summer Time",value="NOVST"),
    #         create_choice(name="Novosibirsk Time",value="NOVT"),
    #         create_choice(name="Nepal Time",value="NPT"),
    #         create_choice(name="Newfoundland Standard Time",value="NST"),
    #         create_choice(name="Niue Time",value="NUT"),
    #         create_choice(name="New Zealand Daylight Time",value="NZDT"),
    #         create_choice(name="New Zealand Standard Time",value="NZST"),
    #         create_choice(name="Oscar Time Zone",value="O"),
    #         create_choice(name="Omsk Summer Time",value="OMSST"),
    #         create_choice(name="Omsk Standard Time",value="OMST"),
    #         create_choice(name="Papa Time Zone",value="P"),
    #         create_choice(name="Pacific Daylight Time",value="PDT"),
    #         create_choice(name="Peru Time",value="PET"),
    #         create_choice(name="Kamchatka Summer Time",value="PETST"),
    #         create_choice(name="Kamchatka Time",value="PETT"),
    #         create_choice(name="Papua New Guinea Time",value="PGT"),
    #         create_choice(name="Phoenix Island Time",value="PHOT"),
    #         create_choice(name="Philippine Time",value="PHT"),
    #         create_choice(name="Pakistan Standard Time",value="PKT"),
    #         create_choice(name="Pierre & Miquelon Daylight Time",value="PMDT"),
    #         create_choice(name="Pierre & Miquelon Standard Time",value="PMST"),
    #         create_choice(name="Pohnpei Standard Time",value="PONT"),
    #         create_choice(name="Pacific Standard Time",value="PST"),
    #         create_choice(name="Pitcairn Standard Time",value="PST"),
    #         create_choice(name="Tiempo del PacÃ­fico",value="PT"),
    #         create_choice(name="Palau Time",value="PWT"),
    #         create_choice(name="Paraguay Summer Time",value="PYST"),
    #         create_choice(name="Paraguay Time",value="PYT"),
    #         create_choice(name="Quebec Time Zone",value="Q"),
    #         create_choice(name="Reunion Time",value="RET"),
    #         create_choice(name="Sierra Time Zone",value="S"),
    #         create_choice(name="Samara Time",value="SAMT"),
    #         create_choice(name="South Africa Standard Time",value="SAST"),
    #         create_choice(name="Solomon IslandsTime",value="SBT"),
    #         create_choice(name="Seychelles Time",value="SCT"),
    #         create_choice(name="Singapore Time",value="SGT"),
    #         create_choice(name="Suriname Time",value="SRT"),
    #         create_choice(name="Samoa Standard Time",value="SST"),
    #         create_choice(name="Tango Time Zone",value="T"),
    #         create_choice(name="Tahiti Time",value="TAHT"),
    #         create_choice(name="French Southern and Antarctic Time",value="TFT"),
    #         create_choice(name="Tajikistan Time",value="TJT"),
    #         create_choice(name="Tokelau Time",value="TKT"),
    #         create_choice(name="East Timor Time",value="TLT"),
    #         create_choice(name="Turkmenistan Time",value="TMT"),
    #         create_choice(name="Tuvalu Time",value="TVT"),
    #         create_choice(name="Uniform Time Zone",value="U"),
    #         create_choice(name="Ulaanbaatar Time",value="ULAT"),
    #         create_choice(name="Coordinated Universal Time",value="UTC"),
    #         create_choice(name="Uruguay Summer Time",value="UYST"),
    #         create_choice(name="Uruguay Time",value="UYT"),
    #         create_choice(name="Uzbekistan Time",value="UZT"),
    #         create_choice(name="Victor Time Zone",value="V"),
    #         create_choice(name="Venezuelan Standard Time",value="VET"),
    #         create_choice(name="Vladivostok Summer Time",value="VLAST"),
    #         create_choice(name="Vladivostok Time",value="VLAT"),
    #         create_choice(name="Vanuatu Time",value="VUT"),
    #         create_choice(name="Whiskey Time Zone",value="W"),
    #         create_choice(name="West Africa Summer Time",value="WAST"),
    #         create_choice(name="West Africa Time",value="WAT"),
    #         create_choice(name="Western European Summer Time",value="WEST"),
    #         create_choice(name="WesteuropÃ¤ische Sommerzeit",value="WESZ"),
    #         create_choice(name="Western European Time",value="WET"),
    #         create_choice(name="WesteuropÃ¤ische Zeit",value="WEZ"),
    #         create_choice(name="Wallis and Futuna Time",value="WFT"),
    #         create_choice(name="Western Greenland Summer Time",value="WGST"),
    #         create_choice(name="West Greenland Time",value="WGT"),
    #         create_choice(name="Western Indonesian Time",value="WIB"),
    #         create_choice(name="Eastern Indonesian Time",value="WIT"),
    #         create_choice(name="Central Indonesian Time",value="WITA"),
    #         create_choice(name="Western Sahara Summer Time",value="WST"),
    #         create_choice(name="West Samoa Time",value="WST"),
    #         create_choice(name="Western Sahara Standard Time",value="WT"),
    #         create_choice(name="X-ray Time Zone",value="X"),
    #         create_choice(name="Yankee Time Zone",value="Y"),
    #         create_choice(name="Yakutsk Summer Time",value="YAKST"),
    #         create_choice(name="Yakutsk Time",value="YAKT"),
    #         create_choice(name="Yap Time",value="YAPT"),
    #         create_choice(name="Yekaterinburg Summer Time",value="YEKST"),
    #         create_choice(name="Yekaterinburg Time",value="YEKT"),
    #         create_choice(name="Zulu Time Zone",value="Z")
    #     ])])
    # async def _test(self, ctx: SlashContext, option: str):
    #     # with open("user_info.json") as oj: 
    #     # user_info = json.load(oj)
    #     # with open("timezones.json") as oj: 
    #     #     Timezones = json.load(oj)
    #     embed = Embed(title=option)
    #     await ctx.send(embed=embed)

def setup(bot):
    bot.add_cog(fun(bot))
